{"uuid": "4de4131c-7377-4d7e-b11f-9fbfe285bbce", "children": ["772a50e7-c8e0-416d-9da5-ad79e84a8c13"], "befores": [{"name": "browser", "status": "passed", "start": 1667760536721, "stop": 1667760545795}], "afters": [{"name": "browser::fin", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.InvalidSessionIdException: Message: session timed out or not found\n\n", "trace": "  File \"/home/lin/Develop/setup_selenium/venv/lib/python3.8/site-packages/allure_commons/_allure.py\", line 200, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"/home/lin/Develop/setup_selenium/conftest.py\", line 69, in fin\n    driver.quit()\n  File \"/home/lin/Develop/setup_selenium/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 950, in quit\n    self.execute(Command.QUIT)\n  File \"/home/lin/Develop/setup_selenium/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 425, in execute\n    self.error_handler.check_response(response)\n  File \"/home/lin/Develop/setup_selenium/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1667760636347, "stop": 1667760636372}], "start": 1667760536721, "stop": 1667760636373}