{"uuid": "f86795fe-aa52-4737-974d-ad68517d84d4", "children": ["f56bcec3-0e7b-4c2c-a0f0-269f4bcb1d0b"], "befores": [{"name": "browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: Reached error page: about:neterror?e=connectionFailure&u=http%3A//192.168.0.207%3A8081/&c=UTF-8&d=Firefox%20%D0%BD%D0%B5%20%D0%BC%D0%BE%D0%B6%D0%B5%D1%82%20%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%B8%D1%82%D1%8C%20%D1%81%D0%BE%D0%B5%D0%B4%D0%B8%D0%BD%D0%B5%D0%BD%D0%B8%D0%B5%20%D1%81%20%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80%D0%BE%D0%BC%20192.168.0.207%3A8081.\nStacktrace:\nWebDriverError@chrome://remote/content/shared/webdriver/Errors.jsm:188:5\nUnknownError@chrome://remote/content/shared/webdriver/Errors.jsm:515:5\ncheckReadyState@chrome://remote/content/marionette/navigate.js:67:24\nonNavigation@chrome://remote/content/marionette/navigate.js:335:39\nemit@resource://gre/modules/EventEmitter.jsm:162:20\nreceiveMessage@chrome://remote/content/marionette/actors/MarionetteEventsParent.jsm:45:25\n\n", "trace": "  File \"/home/lin/Develop/setup_selenium/venv/lib/python3.8/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/home/lin/Develop/setup_selenium/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/home/lin/Develop/setup_selenium/venv/lib/python3.8/site-packages/_pytest/fixtures.py\", line 890, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"/home/lin/Develop/setup_selenium/conftest.py\", line 60, in browser\n    driver.get(url)\n  File \"/home/lin/Develop/setup_selenium/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 437, in get\n    self.execute(Command.GET, {'url': url})\n  File \"/home/lin/Develop/setup_selenium/venv/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py\", line 425, in execute\n    self.error_handler.check_response(response)\n  File \"/home/lin/Develop/setup_selenium/venv/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1664552295188, "stop": 1664552303209}], "afters": [{"name": "browser::fin", "status": "passed", "start": 1664552303487, "stop": 1664552304583}], "start": 1664552295188, "stop": 1664552304583}